version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: src/AdPlacements.Api/Dockerfile
    container_name: adplacements-api
    ports:
      - "5000:8080"
    environment:
      - DOTNET_ENVIRONMENT=Production
      - Serilog__WriteTo__0__Name=Http
      - Serilog__WriteTo__0__Args__requestUri=http://logstash:8080
      - Serilog__WriteTo__0__Args__textFormatter=Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    volumes:
      - ./ops/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge
